export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_ERROR = 'FETCH_RECIPES_ERROR';

export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';

export const FETCH_FAVOURITES = 'FETCH_FAVOURITES';

export const REMOVE_ALL_FAVOURITES = 'REMOVE_ALL_FAVOURITES';