export const FETCH_ALL_RECIPE_REQUEST = 'FETCH_ALL_RECIPE_REQUEST';
export const FETCH_ALL_RECIPE_SUCCESS = 'FETCH_ALL_RECIPE_SUCCESS';
export const FETCH_ALL_RECIPE_ERROR = 'FETCH_ALL_RECIPE_ERROR';

export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const DELETE_FROM_FAVOURITES = 'DELETE_FROM_FAVOURITES';
